### ISSUE TITLE
TelegrafClient.send crashes when trying to send UTF8 encoded strings

### ISSUE THREAD

**Issue by sbi** [paksu/pytelegraf#3]
As per https://github.com/influxdata/influxdb.com/issues/135, the InfluxDB line protocol character encoding is UTF8. I'm wondering why pytelegraf tries to do an ASCII encoding? Also, shouldn't it test whether data needs to be encoded at all? It I'm noot overlooking something, I'm willing to write a patch and tests for it.

**Comment by paksu** [comment]
Hi @sbi.

I did some research and readings about UTF8 and the line protocol.

The current implementation is pretty naive and it seems that is actually no reason that pytelegraf should encode the output to ascii. 

I looked at the line protocol documentation at https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/ and it says (just like you suggested) that he data, measurement names or tag names can be any unicode strings.

> Line Protocol does not require users to escape the backslash character \. All other special characters also do not require escaping. For example, Line Protocol handles emojis with no problem:

> INSERT we⛅️ther,location=us-midwest temper🔥ture=82 1465839830100400200
> SELECT * FROM "we⛅️ther"

If I understood correctly then the changes you propesed:
- Would be backwards compatible because UTF8 is a superset of ascii. This means that users do not have to change their code.
- And would not require to add any complexity to the pytelegraf API

Meeting both these conditions would be awesome.

Feel free to submit a pull request that adds UTF8 support for metric data, metric names and tags. It would be much appreciated!

**Comment by sbi** [comment]
The way I see it I can indeed meet both conditions. I hope to have this finished soon!

**Comment by sbi** [comment]
Here's a pull request: #5

**Comment by paksu** [comment]
Thank you for reporting and resolving this issue. I have uploaded a new version that contains your fixes 👍

**Comment by sbi** [comment]
Cheers :-)
